#!/usr/bin/env python3

extdir = 'ext'
import sys
import subprocess
import os
sys.path.append(os.path.join(os.path.dirname(__file__), extdir))
from buildtools import KHPRunner
from kninja.runner import *

proj = KProject(extdir = extdir)

directory = proj.builddir('defn/execution')

KDefinition( proj
           , alias = 'execution'
           , backend = 'java'
           , directory = proj.builddir('defn/execution')
           )

# KHPDefinition( proj
#              , alias = 'synthesis'
#              , backend = 'java'
#              , directory = proj.builddir('defn/synthesis')
#              )

KHPRunner(proj).main()
